r6pedia/blog/urls.py
from django.urls import path
from .views import( Homepage,
                    Blog,
                    PostDetail,
                    CategoryList )

app_name = "blog"
urlpatterns = [
    path('home/', Homepage.as_view(), name="homepage"),
    path('', Blog.as_view(), name="blog"),
    path('page/<int:page>', Blog.as_view(), name="blog"),
    path('blog/<slug:slug>', PostDetail.as_view(), name="single-post"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
]

r6pedia/r6pedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog import views as blog_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('aboutus/', blog_views.about, name="about"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

r6pedia/blog/models.py
from django.db import models
from django.utils import timezone
from extentions.utils import jalaliazer

#Managers
class PostManager(models.Manager):
    def published(self):
        return self.filter(status="p")

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status='pub')

#Models
class Category(models.Model):
    rank_choices = [
        ('1', "first"),
        ('2', "second"  ),
        ('3', "third"  ),
        ('4', "fourth"  ),
    ]
    cat_status = [
        ('pub', "Public"),
        ('hid', "Hidden"),
        ('drf', "Drafted"),
    ]
    title       = models.CharField(max_length=50, verbose_name="تیتر")
    parent_cat  = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True, blank=True, related_name="sub_cat", verbose_name="سردسته")
    slug        = models.SlugField(unique=True, max_length=40)
    rank        = models.CharField(max_length=1, choices=rank_choices, verbose_name="رده")
    status      = models.CharField(max_length=3, choices= cat_status, default="pub")

    class Meta:
        verbose_name = "دسته‌بندی"
        verbose_name_plural = "دسته‌بندی ها"
        ordering = ["status"]

    def __str__(self):
        return self.title
    
    objects = CategoryManager()

class Post(models.Model):
    publish_stats_choices = [
        ('p', "published"),
        ('d', "drafted"  ),
    ]
    subject     = models.CharField(max_length=50, verbose_name="تیتر")
    category    = models.ManyToManyField(Category, verbose_name="دسته‌بندی", related_name="posts")
    slug        = models.SlugField(unique=True, max_length=40)
    content     = models.TextField(max_length=100000, verbose_name="مطالب")
    img         = models.ImageField(upload_to="images", verbose_name="تصویر")
    wrote       = models.DateTimeField(auto_now_add=True)
    published   = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    updated     = models.DateTimeField(auto_now=True)
    status      = models.CharField(max_length=1, choices=publish_stats_choices, verbose_name="وضعیت")

    class Meta:
        verbose_name = "پست"
        verbose_name_plural = "پست‌ها"
        ordering = ["-published"]

    def __str__(self):
        return self.subject
    
    def j_published(self):
        return jalaliazer(self.published)
    j_published.short_description = "زمان انتشار"

    def pub_categories(self):
        return self.category.filter(status="pub")

    def str_categories(self):
        return "، ".join([cat.title for cat in self.pub_categories()])
    str_categories.short_description = "دسته‌بندی"


    objects = PostManager()

r6pedia/blog/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView

def about(request):
    return render(request, "blog/about.html")
#--------------------------------------------------------------------

class Homepage(ListView):
    template = "blog/homepage.html"
    def get(self, request, *args, **kwargs):
        return render(request, "blog/homepage.html")
""" 
def homepage(request):
    return render(request, "blog/homepage.html") """
#--------------------------------------------------------------------

class Blog(ListView):
    queryset = Post.objects.published()
    paginate_by = 3
    template_name = "blog/blog_main.html"
    context_object_name = "posts"

""" def blog_main(request):
    posts = Post.objects.published()
    paginator = Paginator(posts, 3)
    page = request.GET.get("page")
    page_posts = paginator.get_page(page)
    context = {
        "posts" : page_posts
    }
    return render(request, "blog/blog_main.html", context) """
#--------------------------------------------------------------------

class PostDetail(DetailView):
    template_name = "blog/single-post.html"
    context_object_name = "post"
    def get_object(self):
        slug = self.kwargs.get("slug")
        return get_object_or_404(Post, slug=slug, status='p')
"""         
def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug, status='p')
    context = {
        "post" : post
    }
    return render(request, "blog/single-post.html", context) """
#--------------------------------------------------------------------

class CategoryList(ListView):
    paginate_by = 3
    template_name = "blog/category.html"
    
    def get_queryset(self):
        slug = self.kwargs.get("slug")
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.posts.published()
    
    def get_context_data(self, **kwargs):
        slug = self.kwargs.get("slug")
        category = get_object_or_404(Category.objects.active(), slug=slug)
        context = super().get_context_data(**kwargs)
        context['category'] =  category
        return context


""" def category(request, slug):
    categories = get_object_or_404(Category, slug=slug, status="pub")
    #posts = categories.posts.published()

    try:
        posts = categories.posts.published()
    except Exception:
        raise Http404

    paginator = Paginator(posts, 3)
    page = request.GET.get("page")
    page_posts = paginator.get_page(page)

    context = {
        "category" : categories,
        "posts" : page_posts,
    }
    return render(request, "blog/category.html", context) """
#--------------------------------------------------------------------

r6pedia/blog/templates/blog/base.html
{% load static %}
{% load main_tags %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        {% if title %}
            <title> IR6 | {{ title }}</title>
        {% else %}
            <title> Iran | Siege</title>
        {% endif %}
<!-- 

-->
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'blog/img/r6-icon.jpg' %}" type="image/jpg">

        <link rel="stylesheet" href="{% static '/blog/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static '/blog/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static '/blog/css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static '/blog/css/light-box.css' %}">
        <link rel="stylesheet" href="{% static '/blog/css/templatemo-style.css' %}">
        <link rel="stylesheet" href="{% static '/blog/css/right-to-left.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Kanit:100,200,300,400,500,600,700,800,900" rel="stylesheet">

        <script src="{% static '/blog/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

<body>
    {% block content %}
    {% endblock content %}

    <footer>
        <div class="container-fluid">
            <div class="col-md-12">
                <p>Copyright &copy; 2018 Company Name 
    
    | Designed by TemplateMo</p>
            </div>
        </div>
    </footer>


      <!-- Modal button -->
    <div class="popup-icon">
      <button id="modBtn" class="modal-btn"><img src="/static/blog/img/contact-icon.png" alt=""></button>
    </div>  

    <!-- Modal -->
    <div id="modal" class="modal">
      <!-- Modal Content -->
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h3 class="header-title">Say hello to <em>Highway</em></h3>
          <div class="close-btn"><img src="/static/blog/img/close_contact.png" alt=""></div>    
        </div>
        <!-- Modal Body -->
        <div class="modal-body">
          <div class="col-md-6 col-md-offset-3">
            <form id="contact" action="" method="post">
                <div class="row">
                    <div class="col-md-12">
                      <fieldset>
                        <input name="name" type="text" class="form-control" id="name" placeholder="Your name..." required>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <input name="email" type="email" class="form-control" id="email" placeholder="Your email..." required>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required></textarea>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="btn">Send Message Now</button>
                      </fieldset>
                    </div>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    

    <section class="overlay-menu">
      <div class="container">
        <div class="row">
          <div class="main-menu">
              <ul>
                  <li>
                      <a href="{% url 'blog:homepage' %}">IR6 || Home </a>
                  </li>
                  <li>
                      <a href="{% url 'blog:blog' %}">IR6 || Blog </a>
                  </li>
                    {% overlay_menu %}
                  <li>
                      <a href="{% url 'about' %}">About Us</a>
                  </li>
              </ul>
              <p>We create awesome templates for you</p>
          </div>
        </div>
      </div>
    </section>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="/static/blog/js/vendor/bootstrap.min.js"></script>
    
    <script src="/static/blog/js/plugins.js"></script>
    <script src="/static/blog/js/main.js"></script>

</body>
</html>

r6pedia/blog/templates/blog/blog_main.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<nav>
    <div class="logo">
        <a href="{% url 'blog:blog' %}">IR6 <em> || Blog</em></a>
    </div>
    <div class="menu-icon">
    <span></span>
    </div>
</nav>

<div class="page-heading">
    <div class="container">
        <div class="heading-content">
            <h1>TEAM <em>Sgt</em></h1>
        </div>
    </div>
</div>

<div class="blog-entries">
    <div class="container">
        <div class="col-md-9">
            <div class="blog-posts">
                <div class="row">
                    <div class="col-md-12">
                        {% for post in posts %}
                            <div class="blog-post">
                                <img src="{{ post.img.url }}" alt="" >
                                <div class="text-content">
                                    <span><a href="#">{{ author }}</a> / <a href="#">{{ post.j_published }}</a> </span>
                                    <h2><a href="{% url 'blog:single-post' post.slug %}">{{ post.subject }} </a> </h2>
                                    <p>{{ post.content | truncatewords:35 }}</p>
                                    <div>
                                        {% for cat in post.pub_categories.all %}
                                            <a href="{% url 'blog:category' cat.slug  %}">#{{ cat }} | </a>
                                        {% endfor %}
                                    </div>
                                    <div class="simple-btn">
                                        <a href="{% url 'blog:single-post' post.slug %}">ادامه</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="col-md-12">
                        <ul class="page-number">
                            {% if is_paginated %}

                                {% if page_obj.has_previous %}
                                    <li ><a href="{% url 'blog:blog' %}?page=1">First</a></li>
                                    <li ><a href="{% url 'blog:blog' page_obj.previous_page_number  %}">Pre</a></li>
                                {% endif %}

                                    <li class="active"><a href="#">{{ page_obj.number }}</a></li>

                                {% if page_obj.has_next %}
                                    <li ><a href="{% url 'blog:blog' page_obj.next_page_number  %}">Next</a></li>
                                    <li ><a href="{% url 'blog:blog' page_obj.paginator.num_pages %}">Last</a></li>

                                {% endif %}

                            {% endif%}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="side-bar">
                <div class="search">
                    <fieldset>
                        <input name="search" type="text" class="form-control" id="search" placeholder="Search..." required>
                    </fieldset>
                </div>
                <div class="archives">
                    <div class="sidebar-heding">
                        <h2>Archives</h2>
                    </div>
                    <ul>
                        <li><a href="#">> 2018 September (4)</a></li>
                        <li><a href="#">> 2018 August (16)</a></li>
                        <li><a href="#">> 2018 July (5)</a></li>
                        <li><a href="#">> 2018 May (3)</a></li>
                        <li><a href="#">> 2018 February (27)</a></li>
                        <li><a href="#">> 2017 December (18)</a></li>
                        <li><a href="#">> 2017 November (12)</a></li>
                    </ul>
                </div>
                <div class="recent-posts">
                    <div class="sidebar-heding">
                        <h2>Recent Posts</h2>
                    </div>
                    <ul>
                        <li><a href="single-post.html">
                            <img src="{% static 'blog/img/recent_post_1.png' %}" alt="Recent Post 1">
                            <div class="text">
                                <h6>Duis mollis orci</h6>
                                <span>15 September 2018</span>
                            </div>
                        </li></a>
                        <li><a href="single-post.html">
                            <img src="{% static 'blog/img/recent_post_2.png' %}" alt="Recent Post 2">
                            <div class="text">
                                <h6>Etiam quis tem</h6>
                                <span>10 August 2018</span>
                            </div>
                        </li></a>
                        <li><a href="single-post.html">
                            <img src="{% static 'blog/img/recent_post_3.png' %}" alt="Recent Post 3">
                            <div class="text">
                                <h6>Proin at augue</h6>
                                <span>16 July 2018</span>
                            </div>
                        </li></a>
                    </ul>
                </div>
                <div class="categories">
                    <div class="sidebar-heding">
                        <h2>Categories</h2>
                    </div>
                    <ul>
                        <li><a href="#">> Lifestyle (7)</a></li>
                        <li><a href="#">> Branding (9)</a></li>
                        <li><a href="#">> Nature (14)</a></li>
                        <li><a href="#">> Work Stuff (6)</a></li>
                        <li><a href="#">> Science (5)</a></li>
                    </ul>
                </div>
                <div class="latest-gallery">
                    <div class="sidebar-heding">
                        <h2>Latest Gallery</h2>
                    </div>
                    <ul>
                        <li><a href="#"></a><img src="img/latest_gallery_1.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_2.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_3.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_4.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_5.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_6.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_7.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_8.png" alt=""></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

r6pedia/blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<nav>
    <div class="logo">
        <a href="{% url 'blog:blog' %}">IR6 <em> || Blog</em></a>
    </div>
    <div class="menu-icon">
    <span></span>
    </div>
</nav>

<div class="page-heading">
    <div class="container">
        <div class="heading-content">
            <h1>{{ category }}</em></h1>
        </div>
    </div>
</div>

<div class="blog-entries">
    <div class="container">
        <div class="col-md-9">
            <div class="blog-posts">
                <div class="row">
                    
                    <div class="col-md-12">
                        {% for post in object_list %}
                            <div class="blog-post">
                                <img src="{{ post.img.url }}" alt="" >
                                <div class="text-content">
                                    <span><a href="#">{{ author }}</a> / <a href="#">{{ post.j_published }}</a> </span>
                                    <h2><a href="{% url 'blog:single-post' post.slug %}">{{ post.subject }} </a> </h2>
                                    <p>{{ post.content | truncatewords:35 }}</p>
                                    <div>
                                        {% for cat in post.pub_categories.all %}
                                            <a href="{% url 'blog:category' cat.slug  %}">#{{ cat }} | </a>
                                        {% endfor %}
                                    </div>
                                    <div class="simple-btn">
                                        <a href="{% url 'blog:single-post' post.slug %}">ادامه</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    
                    <div class="col-md-12">
                        <ul class="page-number">
                            {% if is_paginated %}

                                {% if page_obj.has_previous %}
                                    <li ><a href="{% url 'blog:category' category.slug %}?page=1">First</a></li>
                                    <li ><a href="{% url 'blog:category' category.slug page_obj.previous_page_number %}">Previous</a></li>
                                {% endif %}

                                    <li class="active"><a href="#">{{ page_obj.number }}</a></li>

                                {% if page_obj.has_next %}
                                    <li ><a href="{% url 'blog:category' category.slug page_obj.next_page_number %}">Next</a></li>
                                    <li ><a href="{% url 'blog:category' category.slug page_obj.paginator.num_pages %}">Last</a></li>
                                {% endif %}

                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="side-bar">
                <div class="search">
                    <fieldset>
                        <input name="search" type="text" class="form-control" id="search" placeholder="Search..." required>
                    </fieldset>
                </div>
                <div class="archives">
                    <div class="sidebar-heding">
                        <h2>Archives</h2>
                    </div>
                    <ul>
                        <li><a href="#">> 2018 September (4)</a></li>
                        <li><a href="#">> 2018 August (16)</a></li>
                        <li><a href="#">> 2018 July (5)</a></li>
                        <li><a href="#">> 2018 May (3)</a></li>
                        <li><a href="#">> 2018 February (27)</a></li>
                        <li><a href="#">> 2017 December (18)</a></li>
                        <li><a href="#">> 2017 November (12)</a></li>
                    </ul>
                </div>
                <div class="recent-posts">
                    <div class="sidebar-heding">
                        <h2>Recent Posts</h2>
                    </div>
                    <ul>
                        <li><a href="single-post.html">
                            <img src="{% static 'blog/img/recent_post_1.png' %}" alt="Recent Post 1">
                            <div class="text">
                                <h6>Duis mollis orci</h6>
                                <span>15 September 2018</span>
                            </div>
                        </li></a>
                        <li><a href="single-post.html">
                            <img src="{% static 'blog/img/recent_post_2.png' %}" alt="Recent Post 2">
                            <div class="text">
                                <h6>Etiam quis tem</h6>
                                <span>10 August 2018</span>
                            </div>
                        </li></a>
                        <li><a href="single-post.html">
                            <img src="{% static 'blog/img/recent_post_3.png' %}" alt="Recent Post 3">
                            <div class="text">
                                <h6>Proin at augue</h6>
                                <span>16 July 2018</span>
                            </div>
                        </li></a>
                    </ul>
                </div>
                <div class="categories">
                    <div class="sidebar-heding">
                        <h2>Categories</h2>
                    </div>
                    <ul>
                        <li><a href="#">> Lifestyle (7)</a></li>
                        <li><a href="#">> Branding (9)</a></li>
                        <li><a href="#">> Nature (14)</a></li>
                        <li><a href="#">> Work Stuff (6)</a></li>
                        <li><a href="#">> Science (5)</a></li>
                    </ul>
                </div>
                <div class="latest-gallery">
                    <div class="sidebar-heding">
                        <h2>Latest Gallery</h2>
                    </div>
                    <ul>
                        <li><a href="#"></a><img src="img/latest_gallery_1.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_2.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_3.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_4.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_5.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_6.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_7.png" alt=""></a></li>
                        <li><a href="#"></a><img src="img/latest_gallery_8.png" alt=""></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

r6pedia/blog/templates/blog/homepage.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}


<nav>
    <div class="logo">
        <a href="{% url 'blog:homepage' %}">IR <em> | Siege</em></a>
    </div>
    <div class="menu-icon">
    <span></span>
  </div>
</nav>

<div id="video-container">
    <div class="video-overlay"></div>
    <div class="video-content">
        <div class="inner">

            <div class="scroll-icon">
                <a class="scrollTo" data-scrollTo="portfolio" href="#"><img src="{% static 'blog/img/scroll-icon.png' %}" alt=""></a>
            </div>    
        </div>
    </div>
    <video autoplay loop muted>
        <source src="{% static 'blog/stadium_intro.mp4' %}" type="video/mp4" />
    </video>
</div>

<div class="grid-portfolio" id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                {% for cat in categories %}
                <div class="portfolio-item">
                    <div class="thumb">
                        <a href="{% static 'blog/img/big_portfolio_item_4.jpg' %}" data-lightbox="image-1"><div class="hover-effect">
                            <div class="hover-content">
                                <h1>{{ cat }} <em>squid</em></h1>
                                <p>Awesome Subtittle Goes Here</p>
                            </div>
                        </div></a>
                        <div class="image">
                            <img src="{% static 'blog/img/portfolio_item_4.jpg' %}">
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            
            
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="load-more-button">
                    <a href="#">Load More</a>
                </div>
            </div>
        </div>
        
    </div>
</div>
{% endblock %}

r6pedia/blog/templates/blog/tags-tmpl/overlay_catmenu_loop.html
<li>
    {% for subc in subc.sub_cat.active %}
    <li>
      <a href="{% url 'blog:category' subc.slug %}">{{ subc }}</a>
      {% if subc.sub_cat.active %}
        {% include 'blog/tags-tmpl/overlay_catmenu_loop.html' %}
      {% endif %}
    </li>            
    {% endfor %}
  </li>

r6pedia/blog/templates/blog/tags-tmpl/overlay_menu_cats.html
{% for subc in categories %}
  {% if subc.parent_cat == None %}
    <li>
      <a href="{% url 'blog:category' subc.slug %}">{{ subc }}</a>
      {% if subc.sub_cat.active %}
        {% include 'blog/tags-tmpl/overlay_catmenu_loop.html' %}
      {% endif %}
    </li>
  {% endif %}
{% endfor %}